#ifndef _DOSERR_H
#define _DOSERR_H

// https://www.minuszerodegrees.net/websitecopies/Linux.old/docs/interrupts/int-html/rb-3012.htm

enum {
  DOSERR_NONE                                   = 0,
  DOSERR_INVALID_FUNCTION                       = 1,
  DOSERR_FILE_NOT_FOUND                         = 2,
  DOSERR_PATH_NOT_FOUND                         = 3,
  DOSERR_TOO_MANY_OPEN_FILES                    = 4,
  DOSERR_ACCESS_DENIED                          = 5,
  DOSERR_INVALID_HANDLE                         = 6,
  DOSERR_MEMORY_BLOCK_DESTROYED                 = 7,
  DOSERR_INSUFFICIENT_MEMORY                    = 8,
  DOSERR_INVALID_MEMORY_BLOCK_ADDRESS           = 9,
  DOSERR_INVALID_ENVIRONMENT                    = 10,
  DOSERR_INVALID_FORMAT                         = 11,
  DOSERR_INVALID_ACCESS_CODE                    = 12,
  DOSERR_INVALID_DATA                           = 13,
  DOSERR_FIXUP_OVERFLOW                         = 14,
  DOSERR_INVALID_DRIVE                          = 15,
  DOSERR_CANNOT_REMOVE_CURRENT_DIR              = 16,
  DOSERR_NOT_SAME_DEVICE                        = 17,
  DOSERR_NO_MORE_FILES                          = 18,

  DOSERR_DISK_WRITE_PROTECTED                   = 19,
  DOSERR_UNKNOWN_UNIT                           = 20,
  DOSERR_DRIVE_NOT_READY                        = 21,
  DOSERR_UNKNOWN_COMMAND                        = 22,
  DOSERR_DATA_ERROR_CRC                         = 23,
  DOSERR_BAD_STRUCTURE_LENGTH                   = 24,
  DOSERR_SEEK_ERROR                             = 25,
  DOSERR_UNKNOWN_MEDIA_TYPE                     = 26,
  DOSERR_SECTOR_NOT_FOUND                       = 27,
  DOSERR_PRINTER_OUT_OF_PAPER                   = 28,
  DOSERR_WRITE_FAULT                            = 29,
  DOSERR_READ_FAULT                             = 30,
  DOSERR_GENERAL_FAILURE                        = 31,
  DOSERR_SHARING_VIOLATION                      = 32,
  DOSERR_LOCK_VIOLATION                         = 33,
  DOSERR_INVALID_DISK_CHANGE                    = 34,
  DOSERR_FCB_UNAVAILABLE                        = 35,
  DOSERR_BAD_FAT                                = 35,
  DOSERR_SHARING_BUFFER_OVERFLOW                = 36,

  DOSERR_NETWORK_REQUEST_NOT_SUPPORTED          = 50,
  DOSERR_REMOTE_COMPUTER_NOT_LISTENING          = 51,
  DOSERR_DUPLICATE_NAME_ON_NETWORK              = 52,
  DOSERR_NETWORK_NAME_NOT_FOUND                 = 53,
  DOSERR_NETWORK_BUSY                           = 54,
  DOSERR_NETWORK_DEVICE_NO_LONGER_EXISTS        = 55,
  DOSERR_NETWORK_BIOS_COMMAND_LIMIT_EXCEEDED    = 56,
  DOSERR_NETWORK_ADAPTER_HARDWARE_ERROR         = 57,
  DOSERR_INCORRECT_RESPONSE_FROM_NETWORK        = 58,
  DOSERR_UNEXPECTED_NETWORK_ERROR               = 59,
  DOSERR_INCOMPATIBLE_REMOTE_ADAPTER            = 60,
  DOSERR_PRINT_QUEUE_FULL                       = 61,
  DOSERR_QUEUE_NOT_FULL                         = 62,
  DOSERR_NOT_ENOUGH_SPACE_TO_PRINT_FILE         = 63,
  DOSERR_NETWORK_NAME_WAS_DELETED               = 64,

  DOSERR_NETWORK                                = 65,
  DOSERR_NETWORK_DEVICE_TYPE_INCORRECT          = 66,
  DOSERR_NETWORK_NAME_LIMIT_EXCEEDED            = 68,
  DOSERR_NETWORK_SESSION_LIMIT_EXCEEDED         = 69,
  DOSERR_TEMPORARILY_PAUSED                     = 70,
  DOSERR_NETWORK_REQUEST_NOT_ACCEPTED           = 71,
  DOSERR_NETWORK_PRINT_REDIRECTION_PAUSED       = 72,
  DOSERR_NETWORK_SOFTWARE_NOT_INSTALLED         = 73,
  DOSERR_UNEXPECTED_ADAPTER_CLOSE               = 74,
  DOSERR_FILE_EXISTS                            = 80,
  DOSERR_UNDOC_DUPLICATED_FCB                   = 81,
  DOSERR_CANNOT_MAKE_DIRECTORY                  = 82,
};

#endif /* _DOSERR_H */
